-- EMP_ALLOWANCE 테이블 컬럼 추가 (기존 테이블에 추가)
-- 기존 테이블: EMP_ID, ALLOW_CODE, AMOUNT, COM_ID

-- 1. NOTE 컬럼 추가 (비고)
ALTER TABLE EMP_ALLOWANCE ADD NOTE VARCHAR2(200);

-- 2. CREATED_DATE 컬럼 추가 (생성일)
ALTER TABLE EMP_ALLOWANCE ADD CREATED_DATE DATE DEFAULT SYSDATE;

-- 3. UPDATED_DATE 컬럼 추가 (수정일)
ALTER TABLE EMP_ALLOWANCE ADD UPDATED_DATE DATE DEFAULT SYSDATE;

-- 4. 인덱스 생성 (성능 향상)
CREATE INDEX IDX_EMP_ALLOWANCE_EMP ON EMP_ALLOWANCE(EMP_ID, COM_ID);
CREATE INDEX IDX_EMP_ALLOWANCE_CODE ON EMP_ALLOWANCE(ALLOW_CODE);

-- 5. 기존 데이터에 기본값 설정
UPDATE EMP_ALLOWANCE SET NOTE = '자동 등록' WHERE NOTE IS NULL;
UPDATE EMP_ALLOWANCE SET CREATED_DATE = SYSDATE WHERE CREATED_DATE IS NULL;
UPDATE EMP_ALLOWANCE SET UPDATED_DATE = SYSDATE WHERE UPDATED_DATE IS NULL;

COMMIT;

-- 테이블 구조 확인
DESC EMP_ALLOWANCE; 