-- 실제 업계에서 많이 사용하는 급여 항목 등록 스크립트
-- 회사ID: com-101 기준으로 등록

-- 1. 기본급 (기본급)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('BASIC', '기본급', '기본급', 2000000, 'Y', 'com-101', '고정액', '정직원', SYSDATE, '직원의 기본 급여 항목');

-- 2. 연장수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('OVERTIME', '연장수당', '수당', 6000, 'Y', 'com-101', '근무시간 비례', '정직원', SYSDATE, '초과 근무에 대한 추가 지급');

-- 3. 야간수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('NIGHT', '야간수당', '수당', 8000, 'Y', 'com-101', '근무시간 비례', '정직원', SYSDATE, '야간 근무에 대한 추가 지급');

-- 4. 휴일수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('HOLIDAY', '휴일수당', '수당', 10000, 'Y', 'com-101', '근무시간 비례', '정직원', SYSDATE, '휴일 근무에 대한 추가 지급');

-- 5. 식대 (복리후생)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('MEAL', '식대', '복리후생', 200000, 'Y', 'com-101', '고정액', '전체', SYSDATE, '식사 관련 수당');

-- 6. 교통비 (복리후생)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('TRANSPORT', '교통비', '복리후생', 100000, 'Y', 'com-101', '고정액', '전체', SYSDATE, '교통비 관련 수당');

-- 7. 직책수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('POSITION', '직책수당', '수당', 300000, 'Y', 'com-101', '고정액', '정직원', SYSDATE, '직책에 따른 추가 수당');

-- 8. 상여금 (상여)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('BONUS', '상여금', '상여', 0, 'Y', 'com-101', '성과 연동', '정직원', SYSDATE, '성과에 따른 상여금');

-- 9. 국민연금 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('NATIONAL_PENSION', '국민연금', '공제', 4.5, 'Y', 'com-101', '비율', '정직원', SYSDATE, '국민연금 보험료 공제');

-- 10. 건강보험 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('HEALTH_INSURANCE', '건강보험', '공제', 3.545, 'Y', 'com-101', '비율', '정직원', SYSDATE, '건강보험료 공제');

-- 11. 고용보험 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('EMPLOYMENT_INSURANCE', '고용보험', '공제', 0.8, 'Y', 'com-101', '비율', '정직원', SYSDATE, '고용보험료 공제');

-- 12. 산재보험 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('INDUSTRIAL_ACCIDENT', '산재보험', '공제', 0.8, 'Y', 'com-101', '비율', '정직원', SYSDATE, '산업재해보험료 공제');

-- 13. 소득세 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('INCOME_TAX', '소득세', '공제', 0, 'Y', 'com-101', '비율', '전체', SYSDATE, '소득세 공제');

-- 14. 지방소득세 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('LOCAL_INCOME_TAX', '지방소득세', '공제', 0, 'Y', 'com-101', '비율', '전체', SYSDATE, '지방소득세 공제');

-- 15. 지각공제 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('LATE_FEE', '지각공제', '공제', 50000, 'Y', 'com-101', '고정액', '전체', SYSDATE, '지각 시 공제되는 금액');

-- 16. 조퇴공제 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('EARLY_LEAVE_FEE', '조퇴공제', '공제', 50000, 'Y', 'com-101', '고정액', '전체', SYSDATE, '조퇴 시 공제되는 금액');

-- 17. 결근공제 (공제)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('ABSENT_FEE', '결근공제', '공제', 100000, 'Y', 'com-101', '고정액', '전체', SYSDATE, '결근 시 공제되는 금액');

-- 18. 연차수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('ANNUAL_LEAVE', '연차수당', '수당', 0, 'Y', 'com-101', '비율', '정직원', SYSDATE, '연차 미사용 시 지급되는 수당');

-- 19. 장기근속수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('LONG_SERVICE', '장기근속수당', '수당', 100000, 'Y', 'com-101', '고정액', '정직원', SYSDATE, '장기근속 사원에 대한 수당');

-- 20. 전근수당 (수당)
INSERT INTO SALARYITEM (ALLOW_CODE, ALLOW_NAME, TYPE, DEFAULT_AMOUNT, ACCT_YN, COM_ID, CALC_TYPE, WORK_TYPES, CREATED_DATE, NOTE) 
VALUES ('PERFECT_ATTENDANCE', '전근수당', '수당', 50000, 'Y', 'com-101', '고정액', '전체', SYSDATE, '전근 시 지급되는 수당');

-- COMMIT
COMMIT;

-- 등록된 급여 항목 확인
SELECT 
    ALLOW_CODE as "항목코드",
    ALLOW_NAME as "항목명",
    TYPE as "카테고리",
    CALC_TYPE as "계산방식",
    DEFAULT_AMOUNT as "기본금액",
    ACCT_YN as "사용여부",
    WORK_TYPES as "적용대상",
    NOTE as "비고"
FROM SALARYITEM 
WHERE COM_ID = 'com-101' 
ORDER BY TYPE, ALLOW_CODE; 